name: Bug Report
description: DO NOT OPEN A DUPLICATE
title: "[Bug]: "

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues and checked the recent builds/commits
          required: true
  - type: markdown
    attributes:
      value: |
        *Please fill this form with as much information as possible, don't forget to fill "What OS..." and "What browsers" and *provide screenshots if possible**
  - type: textarea
    id: what-did
    attributes:
      label: What happened?
      description: Tell us what happened in a very clear and simple way
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step by step information on how to reproduce the bug
      value: |
        1. Go to ....
        2. Press ....
        3. ...
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: What should have happened?
      description: Tell what you think the normal behavior should be
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version where the problem happens
      description: "`python3 -m pip show revChatGPT`"
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: What Python version are you running this with?
      description: "`python3 -V`"
  - type: dropdown
    id: platforms
    attributes:
      label: What is your operating system ?
      multiple: true
      options:
        - Windows
        - Linux
        - MacOS
        - iOS
        - Android
        - Other/Cloud
  - type: textarea
    id: cmdargs
    attributes:
      label: Command Line Arguments
      description: Are you using any launching parameters/command line arguments (modified webui-user .bat/.sh) ? If yes, please write them below. Write "No" otherwise.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Console logs
      description: Please provide **full** cmd/terminal logs from the moment you started UI to the end of it, after your bug happened. If it's very long, provide a link to pastebin or similar service.
      render: Shell
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: Additional information
      description: Please provide us with any relevant additional info or context.
